export const MEALS = [
  {
    "tag": '經典肉類料理',
    meals: [
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3-5',
        originPrice: 400,
        price: 342,
        like: false,
        almost: true,
        done: false,
        new: false,
        hit: true,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '日式照燒豬肉',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: true,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
    ]
  },
  {
    "tag": '海鮮蔬食料理',
    meals: [
      {
        img: 'https://source.unsplash.com/300x300/?seafood',
        title: '海鮮蔬食料理海鮮蔬食料理海鮮蔬食料理海鮮蔬食料理',
        time: 15,
        scale: '3-5',
        originPrice: 600,
        price: 542,
        like: true,
        almost: false,
        done: true,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?seafood',
        title: '海鮮蔬食料理',
        time: 15,
        scale: '3',
        originPrice: null,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: true,
      },
      {
        img: 'https://source.unsplash.com/300x300/?seafood',
        title: '海鮮蔬食料理',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?seafood',
        title: '海鮮蔬食料理',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: true,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?seafood',
        title: '海鮮蔬食料理',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?seafood',
        title: '海鮮蔬食料理',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
    ]
  },
  {
    "tag": '美味湯品',
    meals: [
      {
        img: 'https://source.unsplash.com/300x300/?soup',
        title: '美味湯品',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: true,
      },
      {
        img: 'https://source.unsplash.com/300x300/?soup',
        title: '佛跳牆',
        time: 15,
        scale: '3',
        originPrice: null,
        price: 342,
        like: false,
        almost: false,
        done: true,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?soup',
        title: '家傳麻油雞家傳麻油雞家傳麻油雞家傳麻油雞家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: true,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: true,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?food',
        title: '家傳麻油雞',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: true,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
    ]
  },
  {
    "tag": '主食',
    meals: [
      {
        img: 'https://source.unsplash.com/300x300/?bread',
        title: '油雞飯',
        time: 15,
        scale: '3',
        originPrice: 200,
        price: 142,
        like: false,
        almost: false,
        done: false,
        new: true,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?bread',
        title: '油雞飯',
        time: 15,
        scale: '3',
        originPrice: null,
        price: 342,
        like: false,
        almost: true,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?bread',
        title: '油雞飯油雞飯油雞飯油雞飯',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?bread',
        title: '油雞飯',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: true,
      },
      {
        img: 'https://source.unsplash.com/300x300/?bread',
        title: '油雞飯',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?bread',
        title: '油雞飯',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
    ]
  },
  {
    "tag": '生鮮蔬菜',
    meals: [
      {
        img: 'https://source.unsplash.com/300x300/?vegetable',
        title: '生鮮蔬菜',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: true,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?vegetable',
        title: '生鮮蔬菜',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?vegetable',
        title: '生鮮蔬菜生鮮蔬菜生鮮蔬菜生鮮蔬菜',
        time: 15,
        scale: '3-5',
        originPrice: 800,
        price: 742,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?vegetable',
        title: '生鮮蔬菜',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: false,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?vegetable',
        title: '生鮮蔬菜',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: false,
        done: false,
        new: true,
        hit: false,
      },
      {
        img: 'https://source.unsplash.com/300x300/?vegetable',
        title: '生鮮蔬菜5',
        time: 15,
        scale: '3',
        originPrice: 400,
        price: 342,
        like: false,
        almost: true,
        done: false,
        new: false,
        hit: false,
      },
    ]
  }
]
